default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 5432
  user: bla
  password: yourpassword

development:
  <<: *default
  database: hackathon-argentina_development

test:
  <<: *default
  database: hackathon-argentina_test

production:
  <<: *default
  database: hackathon-argentina_production
  username: hackathon-argentina
  password: <%= ENV['HACKATHON-ARGENTINA_DATABASE_PASSWORD'] %>
